/**
 * Zalo QR Dashboard for OpenClaw
 *
 * This service serves the QR code generated by OpenClaw's native
 * "zalouser" (Zalo Personal) channel. It does NOT do its own Zalo auth;
 * it just presents the QR file that openclaw writes to the shared volume
 * so the user can scan it from a browser.
 */

import express from "express";
import { createServer } from "http";
import { WebSocketServer } from "ws";
import { exec } from "child_process";
import fs from "fs";
import path from "path";

const PORT = 3000;

// Path to the QR image generated by openclaw's zalouser channel
// This file lives in the shared volume openclaw-tmp.
const QR_PATH = process.env.OPENCLAW_QR_PATH || "/openclaw-tmp/openclaw-zalouser-qr-default.png";

const app = express();
const httpServer = createServer(app);
const wss = new WebSocketServer({ server: httpServer });

// ── State ──────────────────────────────────────────────────────────────────
let lastQrMtime = 0;
let qrAvailable = false;

function checkQR() {
  try {
    const stat = fs.statSync(QR_PATH);
    const mtime = stat.mtimeMs;
    if (mtime !== lastQrMtime) {
      lastQrMtime = mtime;
      qrAvailable = true;
      broadcast({ type: "qr_updated" });
      console.log(`[Zalo QR] New QR ready at ${new Date(mtime).toISOString()}`);
    }
  } catch (_) {
    if (qrAvailable) {
      qrAvailable = false;
      broadcast({ type: "qr_unavailable" });
    }
  }
}

// Poll every 5 seconds for new QR
setInterval(checkQR, 5000);
checkQR();

// ── Broadcast ──────────────────────────────────────────────────────────────
function broadcast(msg) {
  const text = JSON.stringify(msg);
  for (const ws of wss.clients) {
    if (ws.readyState === 1) ws.send(text);
  }
}

// ── Routes ─────────────────────────────────────────────────────────────────
app.get("/zalo", (req, res) => res.send(renderPage()));

// Serve the raw QR image with cache-buster support
app.get("/zalo/qr.png", (req, res) => {
  if (!fs.existsSync(QR_PATH)) {
    res.status(404).send("QR not ready yet");
    return;
  }
  res.setHeader("Content-Type", "image/png");
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("X-QR-Timestamp", String(lastQrMtime));
  fs.createReadStream(QR_PATH).pipe(res);
});

// State API
app.get("/zalo/api/state", (req, res) => {
  res.json({
    qrAvailable,
    qrTimestamp: lastQrMtime,
    qrPath: QR_PATH,
  });
});

// Trigger new QR generation via docker exec into the openclaw-bot container.
// The CLI command starts a QR flow and exits (even with error) but openclaw
// generates a fresh QR file as a side-effect. The file watcher picks it up.
app.post("/zalo/api/refresh", (req, res) => {
  res.json({ ok: true, message: "Đang tạo QR mới..." });
  const cmd = "docker exec openclaw-bot openclaw channels login --channel zalouser --account default";
  console.log(`[Zalo QR] Triggering refresh via: ${cmd}`);
  exec(cmd, { timeout: 30000 }, (err) => {
    // The command exits with error (CLI can't reach gateway from container loopback)
    // but openclaw still triggers a new QR generation as a side-effect.
    if (err) console.log("[Zalo QR] exec exited (expected):", err.message?.slice(0, 80));
  });
});

// ── WebSocket ──────────────────────────────────────────────────────────────
wss.on("connection", (ws) => {
  ws.send(JSON.stringify({ type: "state", qrAvailable, qrTimestamp: lastQrMtime }));
});

// ── UI ─────────────────────────────────────────────────────────────────────
function renderPage() {
  return `<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Zalo Login – OpenClaw</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0f0f13;color:#e8e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}
.card{background:#1a1a24;border:1px solid #2a2a3a;border-radius:20px;padding:36px 32px;width:min(460px,100%);text-align:center}
.logo{font-size:26px;font-weight:700;margin-bottom:4px}.logo span{color:#0068ff}
.subtitle{font-size:13px;color:#888;margin-bottom:24px}
.badge{display:inline-flex;align-items:center;gap:6px;padding:5px 14px;border-radius:99px;font-size:12px;font-weight:600;margin-bottom:20px;border:1px solid}
.badge.ready{background:#001433;border-color:#0055aa;color:#4499ff}
.badge.waiting{background:#1a0a00;border-color:#553300;color:#ff9944}
.dot{width:7px;height:7px;border-radius:50%;background:currentColor}
.qr-box{background:#fff;border-radius:14px;padding:14px;display:inline-block;margin:12px 0}
.qr-box img{display:block;width:220px;height:220px}
.hint{font-size:12px;color:#666;margin:8px 0 20px;line-height:1.6}
.hint b{color:#aaa}
.spinner{width:34px;height:34px;border:3px solid #2a2a3a;border-top-color:#0068ff;border-radius:50%;animation:spin .7s linear infinite;margin:18px auto}
@keyframes spin{to{transform:rotate(360deg)}}
.ts{font-size:11px;color:#555;margin-top:6px}
.btn{padding:9px 22px;border-radius:10px;font-size:13px;font-weight:600;cursor:pointer;border:1px solid #333;background:#1e1e2e;color:#aaa;transition:opacity .15s}
.btn:hover{opacity:.8}.btn:active{transform:translateY(1px)}
.btn-gen{background:#0068ff;border-color:#0068ff;color:#fff}
.ws-dot{position:fixed;bottom:10px;right:14px;font-size:11px;color:#444}
.steps{text-align:left;background:#12121e;border:1px solid #2a2a3a;border-radius:12px;padding:14px 16px;margin-top:18px;font-size:13px;line-height:1.8;color:#999}
.steps b{color:#ccc}
.steps .step{display:flex;gap:10px;align-items:flex-start;margin:3px 0}
.num{background:#0068ff;color:#fff;border-radius:50%;width:18px;height:18px;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:1px}
</style>
</head>
<body>
<div class="card">
  <div class="logo">Open<span>Claw</span></div>
  <div class="subtitle">Đăng nhập Zalo Cá Nhân</div>

  <div id="badge" class="badge waiting"><div class="dot"></div><span id="badge-text">Đang chờ QR...</span></div>
  <div id="content">
    <div class="spinner"></div>
    <p style="color:#666;font-size:13px">Đang tải QR code từ OpenClaw...</p>
  </div>

  <div style="margin-top:16px">
    <button class="btn btn-gen" onclick="genQR()" id="btn-gen">⟳ Generate QR mới</button>
  </div>

  <div class="steps" style="margin-top:16px">
    <div class="step"><span class="num">1</span><span>Nhấn <b>Generate QR mới</b> nếu QR hết hạn</span></div>
    <div class="step"><span class="num">2</span><span>Mở <b>Zalo</b> → <b>Quét mã QR</b></span></div>
    <div class="step"><span class="num">3</span><span>Quét mã → <b>Xác nhận</b> trên điện thoại ✓</span></div>
  </div>
</div>
<div id="ws-dot" class="ws-dot">⬤ connecting</div>

<script>
let qrTimestamp = 0;
let refreshTimer = null;

function loadQR() {
  const content = document.getElementById('content');
  const badge = document.getElementById('badge');
  const badgeText = document.getElementById('badge-text');
  const ts = Date.now();

  badge.className = 'badge ready';
  badgeText.textContent = 'QR sẵn sàng – quét ngay!';

  content.innerHTML =
    '<div class="qr-box"><img id="qr-img" src="/zalo/qr.png?t=' + ts + '" width="220" height="220" alt="Zalo QR Code" onerror="onQrError()"></div>' +
    '<p class="hint">QR tự động làm mới khi hết hạn.<br><b>Quét trong vòng ~2 phút.</b></p>' +
    '<div class="ts" id="qr-ts">Cập nhật: ' + new Date().toLocaleTimeString('vi-VN') + '</div>';

  // Auto-refresh every 90s as backup
  clearTimeout(refreshTimer);
  refreshTimer = setTimeout(loadQR, 90000);
}

function showWaiting() {
  const badge = document.getElementById('badge');
  const badgeText = document.getElementById('badge-text');
  badge.className = 'badge waiting';
  badgeText.textContent = 'Đang chờ QR...';
  document.getElementById('content').innerHTML =
    '<div class="spinner"></div><p style="color:#666;font-size:13px">Đang tạo QR code...</p>';
}

function onQrError() {
  showWaiting();
}

async function genQR() {
  const btn = document.getElementById('btn-gen');
  btn.disabled = true;
  btn.textContent = '⟳ Đang tạo...';
  showWaiting();
  try { await fetch('/zalo/api/refresh', { method: 'POST' }); } catch(_) {}
  setTimeout(() => { btn.disabled = false; btn.textContent = '⟳ Generate QR mới'; }, 6000);
}

// WebSocket
function connect() {
  const proto = location.protocol === 'https:' ? 'wss' : 'ws';
  const ws = new WebSocket(proto + '://' + location.host + '/zalo');
  const dot = document.getElementById('ws-dot');
  ws.onopen = () => { dot.textContent = '⬤ live'; dot.style.color = '#2a5'; };
  ws.onclose = () => { dot.textContent = '⬤ offline'; dot.style.color = '#a55'; setTimeout(connect, 3000); };
  ws.onmessage = (ev) => {
    try {
      const msg = JSON.parse(ev.data);
      if (msg.type === 'qr_updated' || (msg.type === 'state' && msg.qrAvailable)) {
        qrTimestamp = msg.qrTimestamp || Date.now();
        loadQR();
      } else if (msg.type === 'qr_unavailable') {
        showWaiting();
      }
    } catch (_) {}
  };
}
connect();

// Initial state check
fetch('/zalo/api/state').then(r => r.json()).then(s => {
  if (s.qrAvailable) { qrTimestamp = s.qrTimestamp; loadQR(); }
}).catch(() => {});
</script>
</body>
</html>`;
}

// ── Start ──────────────────────────────────────────────────────────────────
httpServer.listen(PORT, () => {
  console.log(`[Zalo Dashboard] Port ${PORT}`);
  console.log(`[Zalo Dashboard] Watching QR at: ${QR_PATH}`);
});
